api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            jwt:
                name: 'Authorization'
                type: 'header'
    title: 'Billing'
    description: 'REST API service for billing management.'
    version: '1.0.0'
    show_webby: false